### ISSUE TITLE
Strange styles file

### ISSUE THREAD

**Issue by stoecker** [Sowa1980/tree_validator_Styles#1]
The URL for this you entered creates a 174M file including another large zip file and useless files like Excel. I think you should revise this.

P.S. I also removed the link to the presets file from the styles page. Did you probably want to enter another project instead of the presets file?

**Comment by Sowa1980** [comment]
Hello.
zip files, this was a copy
Excel - this pivot table was needed for the preset in order to mark in it which trees were included in the blank.
I have now removed it from the repository.
on account of this Subscriber_mailbox_preset.zip. Yes, I added it to the wrong page by mistake. thanks for removing the link.

a little later I will reduce the size of this style
​https://github.com/Sowa1980/tree_validator_Styles/archive/master.zip/

by optimizing the cortinos to a smaller size.

Здравствуйте.
Файлы zip , это была копия 
Excel - это сводная таблица была нужна для пресета что бы в ней отмечать какие деревья внесены в заготовку.
Сейчас я это удалил из репозитория.
на счет этого Subscriber_mailbox_preset.zip. Да я по ошибки это добавил не на ту страницу. спасибо что удалили ссылку.

чуть позже еще уменьшу размер данного стиля
​https://github.com/Sowa1980/tree_validator_Styles/archive/master.zip/

путем оптимизации кортинок до меньшего размера.
